### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by Jason123456789** [DragAndWatch/Dragand-App#13]
Drag and Drop isn't working guys

**Comment by Mathew78540** [comment]
Can you give us more details ? Your operating system with the version for exemple.

**Comment by Jason123456789** [comment]
Windows 8.1 Pro. 

When I try to drag and drop an MKV file, it won't show that the file can be dropped anywhere.

**Comment by Mathew78540** [comment]
OK thx, i will try to understand and fix it

**Comment by Jason123456789** [comment]
Hi Mathew, 

Somehow this issue got resolved and now I'm able to drag and drop files.

Thanks!
